/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as MobilePaintRouteImport } from './routes/mobile-paint'
import { Route as MotorbikeRouteImport } from './routes/motorbike'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePaintRoute = MobilePaintRouteImport.update({
  id: '/mobile-paint',
  path: '/mobile-paint',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorbikeRoute = MotorbikeRouteImport.update({
  id: '/motorbike',
  path: '/motorbike',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/mobile-paint': typeof MobilePaintRoute
  '/motorbike': typeof MotorbikeRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/mobile-paint': typeof MobilePaintRoute
  '/motorbike': typeof MotorbikeRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/mobile-paint': typeof MobilePaintRoute
  '/motorbike': typeof MotorbikeRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/mobile-paint'
    | '/motorbike'
    | '/services'
    | '/terms'
    | '/blog'
    | '/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/mobile-paint'
    | '/motorbike'
    | '/services'
    | '/terms'
    | '/blog'
    | '/contact'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/mobile-paint'
    | '/motorbike'
    | '/services'
    | '/terms'
    | '/blog'
    | '/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  MobilePaintRoute: typeof MobilePaintRoute
  MotorbikeRoute: typeof MotorbikeRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-paint': {
      id: '/mobile-paint'
      path: '/mobile-paint'
      fullPath: '/mobile-paint'
      preLoaderRoute: typeof MobilePaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorbike': {
      id: '/motorbike'
      path: '/motorbike'
      fullPath: '/motorbike'
      preLoaderRoute: typeof MotorbikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  MobilePaintRoute: MobilePaintRoute,
  MotorbikeRoute: MotorbikeRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
